/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'question' : string,
  'answer' : string,
  'timestamp' : Time,
}
export type ExamType = { 'jee' : null } |
  { 'neet' : null } |
  { 'upsc' : null } |
  { 'class10' : null } |
  { 'class12' : null };
export interface Note {
  'title' : string,
  'topic' : string,
  'content' : string,
  'subject' : string,
}
export interface QuizAttempt {
  'questionsAnswered' : bigint,
  'topic' : string,
  'subject' : string,
  'score' : bigint,
}
export interface StudySession {
  'subject' : string,
  'date' : Time,
  'durationMinutes' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'subjects' : Array<string>,
  'name' : string,
  'examType' : ExamType,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[string, string], undefined>,
  'addNote' : ActorMethod<[Note], undefined>,
  'addQuizAttempt' : ActorMethod<[QuizAttempt], undefined>,
  'addStudySession' : ActorMethod<[StudySession], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearUserData' : ActorMethod<[], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'getAllNotes' : ActorMethod<[Principal], Array<Note>>,
  'getAllStudySessions' : ActorMethod<[Principal], Array<StudySession>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getQuizAttempts' : ActorMethod<[], Array<QuizAttempt>>,
  'getStats' : ActorMethod<
    [Principal],
    {
      'avgScore' : bigint,
      'notesCount' : bigint,
      'totalSessions' : bigint,
      'chatCount' : bigint,
    }
  >,
  'getStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchNotes' : ActorMethod<[string], Array<Note>>,
  'updateNote' : ActorMethod<[Note], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];