/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Note = IDL.Record({
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
});
export const QuizAttempt = IDL.Record({
  'questionsAnswered' : IDL.Nat,
  'topic' : IDL.Text,
  'subject' : IDL.Text,
  'score' : IDL.Nat,
});
export const Time = IDL.Int;
export const StudySession = IDL.Record({
  'subject' : IDL.Text,
  'date' : Time,
  'durationMinutes' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExamType = IDL.Variant({
  'jee' : IDL.Null,
  'neet' : IDL.Null,
  'upsc' : IDL.Null,
  'class10' : IDL.Null,
  'class12' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'examType' : ExamType,
});
export const ChatMessage = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addNote' : IDL.Func([Note], [], []),
  'addQuizAttempt' : IDL.Func([QuizAttempt], [], []),
  'addStudySession' : IDL.Func([StudySession], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearUserData' : IDL.Func([], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'getAllNotes' : IDL.Func([IDL.Principal], [IDL.Vec(Note)], ['query']),
  'getAllStudySessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StudySession)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getStats' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'avgScore' : IDL.Nat,
          'notesCount' : IDL.Nat,
          'totalSessions' : IDL.Nat,
          'chatCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'updateNote' : IDL.Func([Note], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Note = IDL.Record({
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
  });
  const QuizAttempt = IDL.Record({
    'questionsAnswered' : IDL.Nat,
    'topic' : IDL.Text,
    'subject' : IDL.Text,
    'score' : IDL.Nat,
  });
  const Time = IDL.Int;
  const StudySession = IDL.Record({
    'subject' : IDL.Text,
    'date' : Time,
    'durationMinutes' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExamType = IDL.Variant({
    'jee' : IDL.Null,
    'neet' : IDL.Null,
    'upsc' : IDL.Null,
    'class10' : IDL.Null,
    'class12' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'examType' : ExamType,
  });
  const ChatMessage = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addNote' : IDL.Func([Note], [], []),
    'addQuizAttempt' : IDL.Func([QuizAttempt], [], []),
    'addStudySession' : IDL.Func([StudySession], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearUserData' : IDL.Func([], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'getAllNotes' : IDL.Func([IDL.Principal], [IDL.Vec(Note)], ['query']),
    'getAllStudySessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getStats' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'avgScore' : IDL.Nat,
            'notesCount' : IDL.Nat,
            'totalSessions' : IDL.Nat,
            'chatCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'updateNote' : IDL.Func([Note], [], []),
  });
};

export const init = ({ IDL }) => { return []; };